{{- range .Values.grafanaStorage }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .name }}-pv"
spec:
  storageClassName: local-storage
  capacity:
    storage: {{ .storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .hostPath }}
---
{{- end }}