{{- range .Values.grafanaStorage }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .name }}-pv"
  labels:
    app.kubernetes.io/name: "{{ .name }}-pv"
spec:
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .hostPath }}
---
{{- end }}