ingressController:
  enabled: false

image:
  repository: kong/kong
  tag: "3.7.1"

deployment:
  hostAliases:
    - ip: 192.168.56.51
      hostnames:
        - kong.piinalpin.lab

# Mount the secret created earlier
secretVolumes:
  - kong-cluster-cert

env:
  admin_gui_url: https://kong.piinalpin.lab
  admin_gui_api_url: https://kong.piinalpin.lab/api
  # Change the secret and set cookie_secure to true if using a HTTPS endpoint
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":true}'
  # This is a control_plane node
  role: control_plane

  # These certificates are used for control plane / data plane communication
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  # Database
  # CHANGE THESE VALUES
  database: postgres
  pg_database: homelab
  pg_user:
    valueFrom:
      secretKeyRef:
        name: postgres-credential
        key: user
  pg_password:
    valueFrom:
      secretKeyRef:
        name: postgres-credential
        key: password
  pg_host: postgresql.database.svc.cluster.local
  pg_schema: kong
  pg_ssl: "off"
  # Kong Manager password
  password: k9s9KgAcDrh4

# certificates:
#   enabled: true
#   issuer: selfsigned-kong.piinalpin.lab
#   cluster:
#     enabled: true
#   admin:
#     enabled: true
#     commonName: kong.piinalpin.lab

# The control plane serves the Admin API
admin:
  enabled: true
  annotations:
    konghq.com/protocol: "https"
  http:
    enabled: true
  tls:
    enabled: true
    parameters:
      - http2
  ingress:
    enabled: true
    annotations:
      konghq.com/strip-path: "true"
      konghq.com/protocols: https
      konghq.com/preserve-host: "true"
      cert-manager.io/issuer: selfsigned-kong.piinalpin.lab
    hostname: kong.piinalpin.lab
    tls: kong.piinalpin.lab-tls
    path: /api
    pathType: Prefix
    ingressClassName: kong

# Clustering endpoints are required in hybrid mode
cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

status:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: true

# Optional features
manager:
  enabled: true
  annotations:
    konghq.com/protocol: "https"
  http:
    enabled: false
  tls:
    enabled: true
    parameters:
      - http2
  ingress:
    enabled: true
    annotations:
      konghq.com/strip-path: "true"
      konghq.com/preserve-host: "true"
      konghq.com/protocols: https
      cert-manager.io/issuer: selfsigned-kong.piinalpin.lab
    hostname: kong.piinalpin.lab
    tls: kong.piinalpin.lab-tls
    path: /
    pathType: Prefix
    ingressClassName: kong

# These roles will be served by different Helm releases
proxy:
  enabled: false