ingressController:
  enabled: true
  env:
    publish_service: kong/kong-dp-kong-proxy
    kong_admin_token: k9s9KgAcDrh4
  
image:
  repository: kong/kong
  tag: "3.7.1"
  
# Mount the secret created earlier
secretVolumes:
  - kong-cluster-cert

deployment:
  hostAliases:
    - ip: 192.168.56.51
      hostnames:
        - kong-admin.piinalpin.lab
  
env:
  admin_gui_url: http://kong-manager.piinalpin.lab
  admin_gui_api_url: http://kong-admin.piinalpin.lab
  # Change the secret and set cookie_secure to true if using a HTTPS endpoint
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'
  # This is a control_plane node
  role: control_plane
  # These certificates are used for control plane / data plane communication
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  
  # Database
  # CHANGE THESE VALUES
  database: postgres
  pg_database: homelab
  pg_user:
    valueFrom:
      secretKeyRef:
        name: postgres-credential
        key: user
  pg_password:
    valueFrom:
      secretKeyRef:
        name: postgres-credential
        key: password
  pg_host: postgresql.database.svc.cluster.local
  pg_schema: kong
  pg_ssl: "off"
    
  # Kong Manager password
  password: k9s9KgAcDrh4
  
# Enterprise functionality
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
  
# The control plane serves the Admin API
admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: kong-admin.piinalpin.lab
    path: /
    pathType: Prefix
    ingressClassName: kong
  
# Clustering endpoints are required in hybrid mode
cluster:
 enabled: true
 tls:
   enabled: true
  
clustertelemetry:
 enabled: true
 tls:
   enabled: true
  
# Optional features
manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
     
  ingress:
    enabled: true
    hostname: kong-manager.piinalpin.lab
    path: /
    pathType: Prefix
    ingressClassName: kong
  
# These roles will be served by different Helm releases
proxy:
 enabled: false