
storage:
  trace:
    backend: s3
    s3:
      access_key: grafana-tempo
      secret_key: grafana-tempo-secret
      bucket: grafana-tempo
      endpoint: minio.minio.svc.cluster.local:9001
      insecure: true

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false