apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.kafka.service.type }}
  selector:
    app: kafka
  ports:
    {{- toYaml .Values.kafka.service.ports | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      name: client
    - protocol: TCP
      port: 2888
      name: follower
    - protocol: TCP
      port: 3888
      name: election
---
{{- if .Values.kafdrop.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: kafdrop
  ports:
    - protocol: TCP
      port: {{ .Values.kafdrop.service.port }}
      targetPort: 9000
      name: http
{{- end }}