apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-storage"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-storage"
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath }}