apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.credentials.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.credentials.dbUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.credentials.dbPassword | b64enc }}