apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
stringData:
  POSTGRES_DB: my_database
  POSTGRES_USER: adminrnd
  POSTGRES_PASSWORD: gWl7Jj3eZbFEhBqg