apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}