grafanaStorage:
  - name: data-01
    hostPath: /home/k8s/monitoring/data-01
    capacity: 10Gi
    storageClassName: rook-ceph-block
  - name: data-02
    hostPath: /home/k8s/monitoring/data-02
    capacity: 10Gi
    storageClassName: rook-ceph-block
  - name: data-03
    hostPath: /home/k8s/monitoring/data-03
    capacity: 10Gi
    storageClassName: rook-ceph-block

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: grafana.piinalpin.lab
      paths:
        - path: /
          pathType: Prefix
          port: 80
          serviceName: grafana
  tls: []