grafanaStorage:
  - name: prometheus
    hostPath: /home/k8s/monitoring
    capacity: 15Gi
    storageClassName: rook-ceph-block
  - name: alertmanager
    hostPath: /home/k8s/monitoring
    capacity: 100Mi
    storageClassName: rook-ceph-block
  - name: grafana
    hostPath: /home/k8s/monitoring
    capacity: 10Gi
    storageClassName: rook-ceph-block

istio:
  hosts:
    - name: grafana
      host: grafana.piinalpin.lab
      port: 80
      serviceName: grafana
    - name: prometheus
      host: prometheus.piinalpin.lab
      port: 9090
      serviceName: prometheus-prometheus