grafanaStorage:
  - name: prometheus
    hostPath: /home/k8s/monitoring
    capacity: 15Gi
    storageClassName: rook-ceph-block
  - name: alertmanager
    hostPath: /home/k8s/monitoring
    capacity: 100Mi
    storageClassName: rook-ceph-block
  - name: grafana
    hostPath: /home/k8s/monitoring
    capacity: 10Gi
    storageClassName: rook-ceph-block

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: grafana.piinalpin.lab
      paths:
        - path: /
          pathType: Prefix
          port: 80
          serviceName: grafana
    - host: prometheus.piinalpin.lab
      paths:
        - path: /
          pathType: Prefix
          port: 9090
          serviceName: prometheus-prometheus
  tls: []