grafanaStorage:
  - name: alertmanager
    hostPath: /home/k8s/monitoring
    capacity: 100Mi
    storageClassName: rook-ceph-block
  - name: grafana
    hostPath: /home/k8s/monitoring
    capacity: 10Gi
    storageClassName: rook-ceph-block

gateway:
  enabled: true
  annotations:
    konghq.com/strip-path: 'true'
  parentRefs:
    - name: kong
      namespace: default
  hosts:
    - name: grafana
      host: grafana.piinalpin.lab
      service: grafana
      port: 80
    - name: prometheus
      host: prometheus.piinalpin.lab
      service: prometheus-prometheus
      port: 9090