apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-app-ca-certificate
  namespace: default
spec:
  secretName: demo-app-ca-tls
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: demo-app
  duration: 70128h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: demo-app-ca-issuer
  namespace: default
spec:
  ca:
    secretName: demo-app-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-app-certmanager-cert
  namespace: default
spec:
  secretName: demo-app-tls
  issuerRef:
    name: demo-app-ca-issuer
  commonName: demo-app.piinalpin.lab
  duration: 70128h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - demo-app.piinalpin.lab