apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong-ca-certificate
  namespace: kong
spec:
  secretName: kong-ca-tls
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: Kong
  duration: 70128h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kong-ca-issuer
  namespace: kong
spec:
  ca:
    secretName: kong-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certmanager-cert
  namespace: kong
spec:
  secretName: kong-tls
  issuerRef:
    name: kong-ca-issuer
  commonName: kong.piinalpin.lab
  duration: 70128h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - kong.piinalpin.lab
    - kong-cp-kong-cluster.kong.svc.cluster.local
    - kong-cp-kong-clustertelemetry.kong.svc.cluster.local