apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tenant-1-ca-certificate
  namespace: storage
spec:
  secretName: minio-tenant-1-ca-tls
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: minio-tenant
  duration: 70128h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: minio-tenant-ca-issuer
  namespace: storage
spec:
  ca:
    secretName: minio-tenant-1-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tenant-certmanager-cert
  namespace: storage
spec:
  secretName: minio-tls
  issuerRef:
    name: minio-tenant-ca-issuer
  commonName: minio.piinalpin.lab
  duration: 70128h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - minio.storage
    - minio.storage.svc
    - minio.storage.svc.cluster.local
    - "*.minio.storage.svc.cluster.local"
    - "*.minio-hl.storage.svc.cluster.local"
    - minio.piinalpin.lab
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s3-tenant-certmanager-cert
  namespace: storage
spec:
  secretName: s3-tls
  issuerRef:
    name: minio-tenant-ca-issuer
  commonName: s3.piinalpin.lab
  duration: 70128h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - s3.storage
    - s3.storage.svc
    - s3.storage.svc.cluster.local
    - s3.piinalpin.lab