replicaCount: 1

image:
  repository: quay.io/minio/minio
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

storage:
  className: rook-ceph-block
  hostPath: /home/k8s/minio
  capacity: 8Gi

podAnnotations: {}
podLabels:
  app.kubernetes.io/name: minio
  app: minio

service:
  annotations:
    konghq.com/protocol: https
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/host-header: minio.piinalpin.lab
  protocol: https
  type: ClusterIP
  port: 9001

ingress:
  enabled: true
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/protocols: https
    konghq.com/preserve-host: "true"
  hostname: minio.piinalpin.lab
  tls: minio-piinalpin-lab-cert
  path: /
  pathType: Prefix
  ingressClassName: kong

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTPS
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTPS
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3