apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- toYaml .Values.gateway.parentRefs | nindent 4 }}
  hostnames:
  {{- toYaml .Values.gateway.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: "{{ .Release.Name }}-es-http"
          kind: Service
          port: 9200
          namespace: {{ .Release.Namespace }}