apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-storage
  namespace: s3
  labels:
    app: minio
spec:
  storageClassName: rook-ceph-block
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8s/minio
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: minio-claim
#   namespace: s3
#   labels:
#     app: minio
# spec:
#   storageClassName: rook-ceph-block
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi