fullnameOverride: prometheus

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

prometheus:
  enabled: true
  prometheusSpec:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 15Gi
        storageClassName: "rook-ceph-block"
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    hostAliases:
    - ip: "192.168.56.101"
      hostnames:
        - demo-app.piinalpin.lab
    additionalScrapeConfigs: 
      - job_name: blackbox
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://demo-app.piinalpin.lab/dexter/actuator/health
            - http://demo-app.piinalpin.lab/enclave/actuator/health
            - http://demo-app.piinalpin.lab/valkyrie/actuator/health
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
      - job_name: dexter-service
        metrics_path: /dexter/actuator/prometheus
        scrape_interval: 10s
        static_configs:
          - targets: 
            - demo-app.piinalpin.lab
            labels:
              application: Dexter Service
      - job_name: enclave-service
        metrics_path: /enclave/actuator/prometheus
        scrape_interval: 10s
        static_configs:
          - targets: 
            - demo-app.piinalpin.lab
            labels:
              application: Enclave Service
      - job_name: valkyrie-service
        metrics_path: /valkyrie/actuator/prometheus
        scrape_interval: 10s
        static_configs:
          - targets: 
            - demo-app.piinalpin.lab
            labels:
              application: Valkyrie Service

grafana:
  enabled: true
  image:
    tag: 11.1.0
  fullnameOverride: grafana
  defaultDashboardsTimezone: Asia/Jakarta
  serviceMonitor:
    enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: "rook-ceph-block"

alertmanager:
  enabled: true
  fullnameOverride: alertmanager
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Mi
          storageClassName: "rook-ceph-block"

prometheus-node-exporter:
  fullnameOverride: prometheus-node-exporter

kube-state-metrics:
  fullnameOverride: kube-state-metrics