fullnameOverride: prometheus

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

prometheus:
  enabled: true
  prometheusSpec:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 15Gi
        storageClassName: "rook-ceph-block"
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    hostAliases:
    - ip: "192.168.56.101"
      hostnames:
        - demo-app.piinalpin.lab
    additionalScrapeConfigs: 
      - job_name: blackbox
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://demo-app.piinalpin.lab/dexter/actuator/health
            - http://demo-app.piinalpin.lab/enclave/actuator/health
            - http://demo-app.piinalpin.lab/valkyrie/actuator/health
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
  additionalServiceMonitors:
    - name: demo-app-backend-servicemonitor
      selector:
        matchLabels:
          app: demo-app-backend
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: http
          path: /actuator/prometheus
          interval: 10s
          relabelings:
            - sourceLabels: [__meta_kubernetes_service_label_app]
              targetLabel: application
              replacement: "$1"
              action: replace
            - sourceLabels: [__meta_kubernetes_endpoint_address_target_name]
              targetLabel: instance
              replacement: "$1"
              action: replace

grafana:
  enabled: true
  image:
    tag: 11.1.0
  fullnameOverride: grafana
  defaultDashboardsTimezone: Asia/Jakarta
  serviceMonitor:
    enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: "rook-ceph-block"

alertmanager:
  enabled: true
  fullnameOverride: alertmanager
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Mi
          storageClassName: "rook-ceph-block"

prometheus-node-exporter:
  fullnameOverride: prometheus-node-exporter

kube-state-metrics:
  fullnameOverride: kube-state-metrics