fullnameOverride: prometheus

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

prometheus:
  enabled: true
  prometheusSpec:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 15Gi
        storageClassName: "rook-ceph-block"
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    additionalScrapeConfigs: 
      - job_name: backend-apps
        metrics_path: /actuator/prometheus
        scrape_interval: 10s
        static_configs:
          - targets: 
            - 192.168.56.103:8080
            - 192.168.56.104:8080
            - 192.168.56.105:8080
            labels:
              application: Demo Spring Boot Application

grafana:
  enabled: true
  image:
    tag: 11.1.0
  fullnameOverride: grafana
  defaultDashboardsTimezone: Asia/Jakarta
  serviceMonitor:
    enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: "rook-ceph-block"

alertmanager:
  enabled: true
  fullnameOverride: alertmanager
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Mi
          storageClassName: "rook-ceph-block"

prometheus-node-exporter:
  fullnameOverride: prometheus-node-exporter

kube-state-metrics:
  fullnameOverride: kube-state-metrics