image:
  repository: piinalpin/demo-loki-logs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

application:
- name: dexter
  replicaCount: 2
  anotherServiceHost: valkyrie.default.svc.cluster.local
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    labels:
      app: demo-app-backend
- name: enclave
  replicaCount: 1
  anotherServiceHost: dexter.default.svc.cluster.local
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    labels:
      app: demo-app-backend
- name: valkyrie
  replicaCount: 1
  anotherServiceHost: enclave.default.svc.cluster.local
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    labels:
      app: demo-app-backend

tempo:
  host: http://tempo.monitoring.svc.cluster.local:4318

ingress:
  enabled: true
  ingressClassName: kong
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/protocols: https
    konghq.com/preserve-host: "true"
  hostname: demo-app.piinalpin.lab
  tls: demo-app-tls
  hosts:
  - host: demo-app.piinalpin.lab
    paths:
    - path: /dexter
      pathType: Prefix
      service:
        name: dexter
        port: 80
    - path: /enclave
      pathType: Prefix
      service:
        name: enclave
        port: 80
    - path: /valkyrie
      pathType: Prefix
      service:
        name: valkyrie
        port: 80

resources: {}
