apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-kong.piinalpin.lab
  namespace: kong
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong.piinalpin.lab-tls
  namespace: kong
spec:
  secretName: kong.piinalpin.lab-tls
  issuerRef:
    name: selfsigned-kong.piinalpin.lab
    kind: Issuer
  commonName: kong.piinalpin.lab
  duration: 26280h
  renewBefore: 360h
  isCA: true
  subject:
    organizations:
      - Homelab Ltd.
    organizationalUnits:
      - Homelab Ltd.
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - kong.piinalpin.lab
    - kong-cp-kong-cluster.kong.svc.cluster.local
    - kong-cp-kong-clustertelemetry.kong.svc.cluster.local