apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: database
spec:
  serviceName: postgresql
  replicas: 1
  selectors:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
  spec:
    containers:
      - name: postgresql
        image: postgres:15.4
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgresql-config
        - secretRef:
            name: postgresql-secret
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        volumes:
        - name: postgresql-pv
          persistentVolumeClaim:
            claimName: postgresql-pvc