replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "15.4"

imagePullSecrets: []
nameOverride: "postgresql"
fullnameOverride: "postgresql"

service:
  type: LoadBalancer
  port: 5432
  targetPort: 5432
  loadBalancerIP: 192.168.56.52

resources: {}

livenessProbe:
  exec:
    command:
    - pg_isready
    - -U
    - "{{ .Values.credentials.dbUser }}"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  exec:
    command:
    - pg_isready
    - -U
    - "{{ .Values.credentials.dbUser }}"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5

storageClassName: rook-ceph-block
hostPath: /home/k8s/database/postgresql
capacity: 5Gi