{{- range .Values.application}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .name }}-config"
  namespace: {{ $.Release.Namespace }}
data:
  CONTEXT_PATH: ""
  APPLICATION_NAME: {{ .name }}
  ANOTHER_SERVICE_INFO_URL: "http://{{ .anotherServiceHost }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ $.Values.tempo.host }}
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_SERVICE_NAME: {{ .name }}
---
{{- end }}