{{- range .Values.application}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .name }}-config"
  namespace: {{ $.Release.Namespace }}
data:
  CONTEXT_PATH: ""
  APPLICATION_NAME: {{ .name }}
  ANOTHER_SERVICE_INFO_URL: "http://{{ .anotherServiceHost }}.{{ $.Release.Namespace }}.svc.cluster.local:8080/get-another-service-info"
---
{{- end }}