apiVersion: gateway.networking.k8s.io/v1beta1    
kind: ReferenceGrant
metadata:                                    
  name: "{{ .Release.Name }}-grant"
  namespace: {{ .Release.Namespace }}
spec:                        
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute                 
    namespace: default
  to:                     
  - group: ""
    kind: Service