apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: XjOGSTLGeT1g
  KC_DB: postgres
  KC_DB_SCHEMA: keycloak
  KC_DB_URL: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/homelab
  KC_DB_USERNAME: adminrnd
  KC_DB_PASSWORD: gWl7Jj3eZbFEhBqg