apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
stringData:
  KEYCLOAK_ADMIN: {{ .Values.credentials.keycloakAdmin }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.credentials.keycloakAdminPassword }}
  KC_DB: {{ .Values.credentials.keycloakDb }}
  KC_DB_SCHEMA: {{ .Values.credentials.keycloakDbSchema }}
  KC_DB_URL: {{ .Values.credentials.keycloakDbUrl }}
  KC_DB_USERNAME: {{ .Values.credentials.keycloakDbUser }}
  KC_DB_PASSWORD: {{ .Values.credentials.keycloakDbPassword }}