apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}-virtualservice"
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - "{{ .Release.Name }}-gateway"
  http:
  - route:
      - destination:
          port:
            number: {{ .Values.service.port }}
          host: {{ .Release.Name }}
        headers:
            request:
              set:
                x-forwarded-proto: https